In [1]:
## 1. 라이브러리 읽어 들이기 ##

# 텐서플로 라이브러리
import tensorflow as tf
# tflearn 라이브러리
import tflearn
# mnist 데이터 세트를 다루기 위한 라이브러리
import tflearn.datasets.mnist as mnist

import numpy as np

In [2]:
## 2. 데이터 읽어 들이고 전처리하기 ##
# MNIST 데이터를 ./data/mnist에 내려받고, 압축을 해제한 다음 각 변수에 할당하기
trainX, trainY, testX, testY = mnist.load_data('./data/mnist/', one_hot=True)

Extracting ./data/mnist/train-images-idx3-ubyte.gz
Extracting ./data/mnist/train-labels-idx1-ubyte.gz
Extracting ./data/mnist/t10k-images-idx3-ubyte.gz
Extracting ./data/mnist/t10k-labels-idx1-ubyte.gz


In [3]:
# 0번째 이미지의 픽셀 값 출력하기
trainX[0]

array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.  

In [4]:
# 0번째 이미지 픽셀 값의 크기 출력하기
len(trainX[0])

784

In [11]:
# 0번째 이미지의 정답 데이터 출력하기
trainY[0]

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.])

In [6]:
# 이미지 픽셀 데이터를 1차원에서 시계열 데이터로 변환하기
trainX = np.reshape(trainX, (-1, 28, 28))

In [7]:
# 0번째 이미지의 픽셀 값 출력하기
trainX[0]

array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.    

In [8]:
# 0번째 이미지 픽셀 값의 크기 출력하기
len(trainX[0])

28

In [9]:
## 3. 신경망 만들기 ##

## 초기화
tf.reset_default_graph()

## 입력 레이어 만들기
net = tflearn.input_data(shape=[None, 28, 28])

## 중간 레이어 만들기
# LSTM 블록
net = tflearn.lstm(net, 128)

## 출력 레이어 만들기
net = tflearn.fully_connected(net, 10, activation='softmax')
net = tflearn.regression(net, optimizer='sgd', learning_rate=0.5, loss='categorical_crossentropy')

Instructions for updating:
keep_dims is deprecated, use keepdims instead


In [10]:
## 4. 모델 만들기(학습) ##
# 학습 실행하기
model = tflearn.DNN(net)
model.fit(trainX, trainY, n_epoch=20, batch_size=100, validation_set=0.1, show_metric=True)

Training Step: 9899  | total loss: 0.32270 | time: 61.520s
| SGD | epoch: 020 | loss: 0.32270 - acc: 0.9653 -- iter: 49400/49500
Training Step: 9900  | total loss: 0.29100 | time: 63.157s
| SGD | epoch: 020 | loss: 0.29100 - acc: 0.9688 | val_loss: 0.06236 - val_acc: 0.9829 -- iter: 49500/49500
--
