In [1]:
## 1. 라이브러리 읽어 들이기 ##

# 텐서플로 라이브러리
import tensorflow as tf
# tflearn 라이브러리
import tflearn

# 레이어 생성 등 학습에 필요한 라이브러리 읽어 들이기
from tflearn.layers.core import input_data, dropout, fully_connected
from tflearn.layers.conv import conv_2d, max_pool_2d
from tflearn.layers.normalization import local_response_normalization
from tflearn.layers.estimator import regression

# MNIST 데이터 세트를 다루기 위한 라이브러리
import tflearn.datasets.mnist as mnist

import numpy as np

In [2]:
## 2. 데이터 읽어 들이고 전처리하기 ##
# MNIST 데이터를 ./data/mnist에 내려받고, 압축을 해제한 뒤 각 변수에 할당하기
trainX, trainY, testX, testY = mnist.load_data('./data/mnist/', one_hot=True)

Extracting ./data/mnist/train-images-idx3-ubyte.gz
Extracting ./data/mnist/train-labels-idx1-ubyte.gz
Extracting ./data/mnist/t10k-images-idx3-ubyte.gz
Extracting ./data/mnist/t10k-labels-idx1-ubyte.gz


In [3]:
# 첫 번째 이미지가 가진 픽셀값 출력하기
trainX[0]

array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.  

In [4]:
# 첫 번째 이미지가 가진 픽셀값의 크기 출력하기
print(len(trainX[0]))

# 첫 번째 이미지의 정답 데이터 출력하기
print(trainY[0])

784
[ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]


In [5]:
# 이미지 픽셀 데이터를 1차원에서 2차원으로 변환하기
trainX = trainX.reshape([-1, 28, 28, 1])
testX = testX.reshape([-1, 28, 28, 1])

In [6]:
# 첫 번째 픽셀값 출력해보기
trainX[0]

array([[[ 0.        ],
        [ 0.        ],
        [ 0.        ],
        [ 0.        ],
        [ 0.        ],
        [ 0.        ],
        [ 0.        ],
        [ 0.        ],
        [ 0.        ],
        [ 0.        ],
        [ 0.        ],
        [ 0.        ],
        [ 0.        ],
        [ 0.        ],
        [ 0.        ],
        [ 0.        ],
        [ 0.        ],
        [ 0.        ],
        [ 0.        ],
        [ 0.        ],
        [ 0.        ],
        [ 0.        ],
        [ 0.        ],
        [ 0.        ],
        [ 0.        ],
        [ 0.        ],
        [ 0.        ],
        [ 0.        ]],

       [[ 0.        ],
        [ 0.        ],
        [ 0.        ],
        [ 0.        ],
        [ 0.        ],
        [ 0.        ],
        [ 0.        ],
        [ 0.        ],
        [ 0.        ],
        [ 0.        ],
        [ 0.        ],
        [ 0.        ],
        [ 0.        ],
        [ 0.        ],
        [ 0.        ],
        [

In [7]:
# 하나의 픽셀값 크기 출력하기
len(trainX[0])

28

In [8]:
## 3. 신경망 만들기 ##

## 초기화
tf.reset_default_graph()

## 입력 레이어 만들기
net = input_data(shape=[None, 28, 28, 1])

## 중간 레이어 만들기
# 합성곱 레이어 만들기
net = conv_2d(net, 32, 5, activation='relu')
# 풀링 레이어 만들기
net = max_pool_2d(net, 2)
# 합성곱 레이어 만들기
net = conv_2d(net, 64, 5, activation='relu')
# 풀링 레이어 만들기
net = max_pool_2d(net, 2)
# 전결합 레이어 만들기
net = fully_connected(net, 128, activation='relu')
net = dropout(net, 0.5)

## 출력 레이어 만들기
net = tflearn.fully_connected(net, 10, activation='softmax')
net = tflearn.regression(net, optimizer='sgd', learning_rate=0.5, loss='categorical_crossentropy')

Instructions for updating:
Use tf.initializers.variance_scaling instead with distribution=uniform to get equivalent behavior.
Instructions for updating:
keep_dims is deprecated, use keepdims instead


In [9]:
## 4. 모델 만들기(학습) ##
# 학습하기
model = tflearn.DNN(net)
model.fit(trainX, trainY, n_epoch=20, batch_size=100, validation_set=0.1, show_metric=True)

Training Step: 9899  | total loss: 0.62140 | time: 94.713s
| SGD | epoch: 020 | loss: 0.62140 - acc: 0.9662 -- iter: 49400/49500
Training Step: 9900  | total loss: 0.56093 | time: 97.744s
| SGD | epoch: 020 | loss: 0.56093 - acc: 0.9685 | val_loss: 0.02898 - val_acc: 0.9922 -- iter: 49500/49500
--


In [10]:
## 5. 모델 적용하기(예측) ##
pred = np.array(model.predict(testX)).argmax(axis=1)
print(pred)

label = testY.argmax(axis=1)
print(label)

accuracy = np.mean(pred == label, axis=0)
print(accuracy)

[7 2 1 ..., 4 5 6]
[7 2 1 ..., 4 5 6]
0.9921
